### PR TITLE
Create a data model

### PR DESCRIPTION
**Pull request by pinkmoon25**
### Blog app - creating a data model

- Create rails new blog app and initialize with git
- Setup postgres Database
- Create necessary migration files
- Generate the project's schema
- Include foreign key references

### CODE REVIEW

**Comment by prolajumokeoni** [comment]
Hi @PinkMoon25, kindly add a descriptive readme to your pull request, this is required to get a review, you can use the microverse [readme](https://github.com/microverseinc/readme-template) template 👍🏿

**Comment by pinkmoon25** [comment]
hi @prolajumokeoni , I have added the Redme file Thanks :+1:

**Review by prolajumokeoni — APPROVED** [review]
Hi @PinkMoon25, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
## Highlights
- No linter errors ✅ 
- Git flow was used correctly 🚀  
- Good Pr title and description 💪🏿 

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification @prolajumokeoni.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by pinkmoon25** [comment]
Thank you @prolajumokeoni for the review :+1:

**Pull request merged**
